### PR TITLE
Include unistd.h

### PR DESCRIPTION
**Pull request by thcipriani**
## Description

Includes `unistd` in the `SaliencyDetector.cpp` file.
## Explanation

In order for this to compile under Debian using g++ version `g++ (Debian 4.7.2-5) 4.7.2` I had to add `unistd.h` to the `src/SaliencyDetector.cpp` otherwise the `access` function and its constants (`F_OK`, here) were not defined.

I'm not a C or a C++ guy generally so this may not be appropriate for a merge but it worked for me.

### CODE REVIEW

**Comment by mdi** [comment]
:+1:

**Comment by ralrom** [comment]
Thank you, helped me

**Comment by ka-steve** [comment]
Maaan. As a Linux/C noob, win based php programmer, I was trying to install mss-saliency for 2 days to a ubuntu server without luck. And just as I wanted to abandon the project, I wandered around aimlessly and found this, added this one line to the code and it works, so thanks a LOT.
This and Adept are really great tools and kudos to technopagan for them, but the install-experience is just awful.

**Comment by technopagan** [comment]
@thcipriani / Tyler: This is awesome work! Thank you so much for this fix! It's a wonderful OSS community!

**Pull request merged**
